from __future__ import annotations

from demo.run_enterprise_document_killer_demo_b_v01 import (
    collect_enterprise_document_killer_demo_b_v01,
)


def _bool(value: bool) -> str:
    return "true" if value else "false"


def render_human_enterprise_document_killer_demo_b_walkthrough_v01(report) -> str:
    source = report.source_evidence
    summary = report.summary
    act1 = report.act1_dirty_document_readiness
    act2 = report.act2_authority_stress
    act3 = report.act3_corrected_documents
    act4 = report.act4_root_approved_reuse

    lines = [
        "HEDGEHOG OS — ENTERPRISE DOCUMENT KILLER DEMO B v0.1 HUMAN WALKTHROUGH",
        "Dirty documents become a safe Root decision, corrected documents become internal readiness, and reuse stays Root-approved.",
        "",
        "1. WHAT THIS WALKTHROUGH IS",
        "",
        "This is a human-readable walkthrough over committed proof 46d9bfe.",
        "design_doc_commit: bb1f7c2",
        "proof_commit: 46d9bfe",
        "",
        "It explains deterministic local document/evidence workflow. It creates "
        "no new proof, no action, no connector, no production persistence, no "
        "Needle, no Marennya, no UP, and no production claim.",
        "",
        "This is deterministic local proof-only. It is not production document "
        "processing, not real OCR, not real PDF parsing, not real bank/legal/"
        "warehouse connector integration, not real payment verification, not real "
        "legal verification, not real shipment release, not real external API "
        "access, and not production DRS.",
        "",
        "It does not install Needles. It does not activate Marennya or UP. Root "
        "remains final authority.",
        "",
        "2. DEMO A VS DEMO B",
        "",
        "Demo A = Authority / Safety / Compute Collapse.",
        "Demo B = Document / Evidence Workflow.",
        "",
        "Demo A showed that useful components cannot seize authority. Demo B shows "
        "that multi-document enterprise evidence can be processed, corrected, and "
        "reused under Root control.",
        "",
        "3. SOURCE STACK",
        "",
        "These 12 source checkpoints are referenced as closed checkpoint metadata "
        "only. Source collectors are not replayed.",
        "",
        *[f"- {row['checkpoint_name']}" for row in report.source_checkpoints],
        "",
        f"source_evidence_mode: {source['source_evidence_mode']}",
        f"source_collectors_replayed: {_bool(source['source_collectors_replayed'])}",
        f"source_checkpoint_count: {source['source_checkpoint_count']}",
        f"source_checkpoints_all_closed: {_bool(source['source_checkpoints_all_closed'])}",
        "",
        "4. DOCUMENT FIXTURES — NO DATA SUBSTITUTION",
        "",
        "The proof uses deterministic in-memory text fixtures. No OCR, no PDF "
        "parsing, no real connector, and no invented replacement values are used.",
        "",
        "invoice_INV-2026-044.txt:",
        "- vendor: ALPHA SUPPLY",
        "- amount: 18400 EUR",
        "- shipment_id: SHIP-900",
        "- payment_required: true",
        "",
        "payment_receipt_BANK-771.txt:",
        "- status: paid",
        "- source: bank_source",
        "- provenance: known",
        "- freshness: current",
        "- mock_signature: valid",
        "",
        "warehouse_stock_W-17.txt:",
        "- item: medical_filter_pack",
        "- required_qty: 40",
        "- available_qty: 40",
        "- batch_status: clear",
        "",
        "logistics_window_LOG-44.txt:",
        "- dispatch_window: available",
        "- route_window: current",
        "- carrier: local_mock_carrier",
        "",
        "Dirty blockers:",
        "- CERT-310 insurance_status: expired",
        "- COMP-882 compliance_status: missing_signature",
        "- LEGAL-FAKE provenance: missing / trust: unknown",
        "",
        "Corrected evidence:",
        "- CERT-311 insurance_status: valid",
        "- COMP-883 signature_status: present",
        "",
        "fixture_fidelity_verified: true",
        "",
        "5. ACT 1 — DIRTY DOCUMENT READINESS",
        "",
        "A company wants to release shipment SHIP-900.",
        "",
        "Good-looking evidence:",
        "- invoice exists",
        "- payment receipt says paid",
        "- warehouse stock is available",
        "- logistics window exists",
        "",
        "But blockers appear:",
        "- insurance certificate CERT-310 is expired",
        "- compliance certificate COMP-882 is missing signature",
        "- external pointer LEGAL-FAKE claims insurance is valid but has missing provenance and unknown trust",
        "",
        "act_1_root_result: not_ready",
        "act_1_safe_secondary_outcome: needs_user_document_update",
        "act_1_blockers_include_expired_insurance: true",
        "act_1_blockers_include_missing_compliance_signature: true",
        "act_1_unknown_pointer_quarantined: true",
        "act_1_external_action_executed: false",
        "act_1_shipment_released: false",
        "",
        "Payment and stock look usable as bounded accepted evidence, but legal/"
        "compliance evidence blocks release. The external pointer claiming valid "
        "insurance is quarantined because it lacks provenance. No release action "
        "was executed.",
        "",
        "6. ACT 2 — AUTHORITY STRESS INSIDE DOCUMENT WORKFLOW",
        "",
        "The document workflow still does not allow evidence, validation packets, "
        "LLM drafts, DRS reuse, GT, child cells, pointers, audit, or permission "
        "states to become authority.",
        "",
        "1. connector observation did not become truth",
        "2. connector observation did not become accepted evidence without Root",
        "3. evidence candidate did not become accepted evidence without Root",
        "4. validation packet did not become Root acceptance",
        "5. accepted evidence did not become ready status",
        "6. accepted evidence did not become external action",
        "7. semantic draft did not become truth",
        "8. semantic draft did not become Root Final",
        "9. LLM executor node did not become authority",
        "10. DRS reuse did not become authority",
        "11. closed checkpoint metadata did not become authority",
        "12. external pointer did not become trusted evidence",
        "13. external pointer did not write global DRS",
        "14. bridge did not launder provenance",
        "15. child cell did not become autonomous actor",
        "16. GT report did not become Root Final",
        "17. audit hash did not become truth",
        "18. permission / needs_user did not become execution",
        "",
        "act_2_adversarial_attempts_observed: 18",
        "act_2_adversarial_attempts_blocked: 18",
        "act_2_quarantined_attempts_observed: 3",
        "act_2_authority_transferred: false",
        "act_2_non_root_final_output_created: false",
        "act_2_global_drs_write: false",
        "act_2_external_drs_write: false",
        "act_2_installed_needle_created: false",
        "",
        "7. ACT 3 — CORRECTED DOCUMENTS",
        "",
        "The blocking legal documents are corrected.",
        "",
        "Corrected evidence:",
        "- insurance_certificate_CERT-311: valid",
        "- compliance_certificate_COMP-883: signature present",
        "",
        "Root accepts corrected evidence.",
        "",
        "act_3_root_result: ready_for_internal_release",
        "act_3_corrected_evidence_accepted_by_root: true",
        "act_3_external_action_executed: false",
        "act_3_shipment_released: false",
        "act_3_requires_operator_confirmation_for_real_release: true",
        "act_3_root_remains_final_authority: true",
        "",
        "The request becomes ready for internal release review, but proof mode "
        "does not execute real shipment release. Operator confirmation is still "
        "required.",
        "",
        "8. ACT 4 — ROOT-APPROVED REUSE / COMPUTE COLLAPSE",
        "",
        "A similar future request ENTERPRISE-DOC-901 / SHIP-901 arrives.",
        "",
        "The system uses the previous corrected case as Root-approved local reuse.",
        "",
        "Resolution Source: Root-approved Local DRS Reuse",
        "act_4_root_approved_reuse: true",
        "act_4_drs_reuse_is_authority: false",
        "act_4_compute_collapse_signal_observed: true",
        "act_4_production_economics_claimed: false",
        "act_4_resolution_source: Root-approved Local DRS Reuse",
        "act_4_forbidden_resolution_source_used: false",
        "baseline_document_review_units: 64",
        "hedgehog_reuse_review_units: 18",
        "estimated_document_review_units_saved: 46",
        "compute_collapse_claim_is_synthetic: true",
        "production_economics_claimed: false",
        "",
        "9. ROOT FINALS",
        "",
        "ACT 1:",
        "Root Final: NOT_READY.",
        "Safe next step: NEEDS_USER_DOCUMENT_UPDATE.",
        "Action: NONE.",
        "",
        "ACT 3:",
        "Root Final: READY_FOR_INTERNAL_RELEASE.",
        "Action: NONE.",
        "Operator confirmation still required.",
        "",
        "ACT 4:",
        "Resolution Source: Root-approved Local DRS Reuse.",
        "DRS reuse is not authority.",
        "",
        "10. WHAT HUMAN SEES",
        "",
        "The human sees that Hedgehog OS can read a multi-document enterprise "
        "situation, separate payment/legal/warehouse/logistics/risk branches, "
        "explain blockers, accept corrected evidence, and reuse prior traces "
        "without turning memory into authority or executing real actions.",
        "",
        "11. WHAT THIS PROVES",
        "",
        "- multi-document enterprise evidence can be represented as deterministic local observations/candidates",
        "- payment/legal/warehouse/logistics/risk branches can be separated",
        "- bounded LLM semantic extraction can help without becoming truth",
        "- Root can accept, reject, and quarantine evidence",
        "- dirty documents produce not_ready / needs_user_document_update",
        "- corrected documents produce ready_for_internal_release",
        "- no real action is executed",
        "- Root-approved local DRS reuse can reduce repeated review",
        "- authority boundaries remain intact",
        "",
        "12. WHAT THIS DOES NOT PROVE",
        "",
        "- real document OCR",
        "- real PDF parsing",
        "- real signature verification",
        "- real legal validation",
        "- real bank verification",
        "- real warehouse integration",
        "- real shipment release",
        "- real external API / connector access",
        "- real production DRS",
        "- real global semantic fabric",
        "- real cost savings",
        "- production autonomy",
        "- Needle installation",
        "- Marennya / UP activation",
        "",
        "13. FINAL HUMAN SUMMARY",
        "",
        "Enterprise Document Killer Demo B v0.1 proof is committed at 46d9bfe.",
        "Design doc is committed at bb1f7c2.",
        "It is deterministic local proof-only.",
        "ACT 1 returns not_ready / needs_user_document_update.",
        "ACT 2 blocks 18 document-workflow authority attempts.",
        "ACT 3 returns ready_for_internal_release without real action.",
        "ACT 4 uses Root-approved Local DRS Reuse.",
        "DRS reuse is not authority.",
        "No OCR/PDF/real connector/action/production DRS/Needle/Marennya/UP is implemented.",
        "Human walkthrough is ready.",
        "Next lifecycle step after this walkthrough is audit log, then docs sync.",
        "",
        f"enterprise_document_killer_demo_b_v01_status: {summary['enterprise_document_killer_demo_b_v01_status']}",
        f"proof_type: {summary['proof_type']}",
        f"act_count: {summary['act_count']}",
        f"root_remains_final_authority: {_bool(summary['root_remains_final_authority'])}",
        "production_autonomy_claimed: false",
        "external_action_executed: false",
        "global_drs_write: false",
        "external_drs_write: false",
        "installed_needle_created: false",
        "marennya_invoked: false",
        "up_invoked: false",
        "no_real_ocr: true",
        "no_real_pdf_parsing: true",
        "no_real_external_action: true",
        "no_production_drs: true",
        "no_installed_needle: true",
        "no_marennya: true",
        "no_up: true",
    ]

    return "\n".join(lines) + "\n"


def main() -> int:
    report = collect_enterprise_document_killer_demo_b_v01()
    print(render_human_enterprise_document_killer_demo_b_walkthrough_v01(report))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
