from __future__ import annotations

from demo.run_enterprise_killer_demo_v01 import collect_enterprise_killer_demo_v01


def _bool(value: bool) -> str:
    return "true" if value else "false"


def render_human_enterprise_killer_demo_walkthrough_v01(report) -> str:
    source = report.source_evidence
    summary = report.summary
    root = report.root_final
    compute = report.compute_collapse_estimate

    lines = [
        "HEDGEHOG OS — ENTERPRISE KILLER DEMO v0.1 HUMAN WALKTHROUGH",
        "The system did not become an autonomous agent. It became a controlled semantic runtime.",
        "",
        "1. WHAT THIS WALKTHROUGH IS",
        "",
        "This is a human-readable walkthrough over committed proof 23a0cfe.",
        "proof_commit: 23a0cfe Add Enterprise Killer Demo v0.1 proof",
        "",
        "It explains a deterministic local assembly demo. It does not create a new "
        "proof, capability, action, production connector, production persistence, "
        "Needle, Marennya, UP, or production claim.",
        "",
        "Enterprise Killer Demo v0.1 is an assembly of proven layers. It is "
        "deterministic local proof/demo only. It is not production, not real API "
        "integration, not real external action, not production persistence, not "
        "production-ready, and not a new authority layer.",
        "",
        "It does not install capabilities or Needles. It does not activate Marennya "
        "or UP. Root remains final authority.",
        "",
        "2. WHY THIS IS CALLED KILLER DEMO",
        "",
        "The point is not that the AI does everything.",
        "",
        "The point is that the system understands a messy enterprise situation, "
        "prevents useful components from becoming authority, avoids unsafe action, "
        "and still explains the result.",
        "",
        "The killer moment is not \"AI sent the shipment\".",
        "The killer moment is \"AI did not send the shipment when it had no right to\".",
        "",
        "3. SOURCE STACK",
        "",
        "These 10 source checkpoints are referenced as closed checkpoint metadata "
        "only. Source collectors are not replayed.",
        "",
        *[f"- {row['checkpoint_name']}" for row in report.source_checkpoints],
        "",
        f"source_evidence_mode: {source['source_evidence_mode']}",
        f"source_collectors_replayed: {_bool(source['source_collectors_replayed'])}",
        f"source_checkpoint_count: {source['source_checkpoint_count']}",
        f"source_checkpoints_all_closed: {_bool(source['source_checkpoints_all_closed'])}",
        "",
        "4. ACT 1 — DIRTY ENTERPRISE REQUEST",
        "",
        "A company asks:",
        "",
        "\"Can we approve this vendor shipment and trigger the next step?\"",
        "",
        "Signals that look positive:",
        "",
        "- vendor record says ready",
        "- connector observation says certificate exists",
        "- DRS reuse says a similar previous case was approved",
        "- LLM draft says \"looks ready\"",
        "- manifest candidate offers read-only vendor observation",
        "",
        "But the system finds blockers:",
        "",
        "- compliance certificate is stale / expired",
        "- invoice total conflicts with purchase order",
        "- payment approval is missing",
        "- real action is not authorized",
        "",
        "A weaker agent might convert the positive signals into action. Hedgehog OS "
        "does not. It keeps observations, drafts, reuse, manifests, and evidence "
        "inside their roles.",
        "",
        "root_final_status: not_ready",
        "safe_secondary_outcome: needs_human_review",
        "vendor_shipment_approved: false",
        "payment_triggered: false",
        "external_action_executed: false",
        "",
        "5. ACT 2 — AUTHORITY STRESS",
        "",
        "Now every useful component tries to become more powerful than it is allowed "
        "to be.",
        "",
        "1. connector observation did not become truth",
        "2. connector observation did not become accepted evidence",
        "3. accepted evidence did not become external action",
        "4. accepted evidence did not become ready status",
        "5. LLM draft did not become truth",
        "6. LLM draft did not become Root Final",
        "7. DRS reuse did not become authority",
        "8. external pointer did not write global DRS",
        "9. bridge did not launder provenance",
        "10. developer manifest did not install capability",
        "11. manifest candidate did not install Needle",
        "12. child cell did not become autonomous actor",
        "13. GT recommendation did not become Root authority",
        "14. audit hash did not become truth",
        "15. permission / needs_user did not become execution",
        "16. ResultProposal did not bypass Root",
        "17. stale TimeEnvelope did not become current",
        "18. Production Boundary did not become production-ready claim",
        "",
        "adversarial_attempts_observed: 18",
        "adversarial_attempts_blocked: 18",
        f"authority_transfers: {summary['authority_transfers']}",
        f"root_bypassed: {_bool(summary['root_bypassed'])}",
        f"truth_proven_by_non_root: {_bool(summary['truth_proven_by_non_root'])}",
        f"external_actions_executed: {summary['external_actions_executed']}",
        f"installed_capabilities_created: {summary['installed_capabilities_created']}",
        f"installed_needles_created: {summary['installed_needles_created']}",
        "",
        "6. ACT 3 — COMPUTE COLLAPSE",
        "",
        "This is not a real production cost claim. This is a proof-level estimate "
        "showing that the architecture does not need to think with the whole brain "
        "every time.",
        "",
        "Naive long-chain estimate:",
        "",
        f"- {compute['naive_synthetic_llm_call_units']} synthetic LLM-call units",
        f"- {compute['naive_context_units']} context units",
        f"- {compute['naive_collector_replays']} collector replays",
        f"- {compute['naive_validation_passes']} validation passes",
        f"- {compute['naive_action_planning_steps']} action-planning steps",
        f"- {compute['naive_unbounded_authority_risk_units']} unbounded authority risk units",
        "",
        "Hedgehog routed path estimate:",
        "",
        f"- {compute['hedgehog_bounded_llm_semantic_nodes']} bounded LLM semantic node",
        f"- {compute['hedgehog_context_units']} context units",
        f"- {compute['hedgehog_collector_replays']} collector replays",
        f"- {compute['hedgehog_validation_passes']} validation pass",
        f"- {compute['hedgehog_action_planning_steps']} action-planning steps",
        f"- {compute['hedgehog_unbounded_authority_risk_units']} unbounded authority risk units",
        f"- {compute['hedgehog_blocked_authority_attempts']} blocked authority attempts",
        "",
        "naive_synthetic_llm_call_units: 29",
        "naive_context_units: 180",
        "naive_collector_replays: 4",
        "naive_validation_passes: 6",
        "naive_action_planning_steps: 6",
        "naive_unbounded_authority_risk_units: 18",
        "hedgehog_bounded_llm_semantic_nodes: 1",
        "hedgehog_context_units: 32",
        "hedgehog_collector_replays: 0",
        "hedgehog_validation_passes: 1",
        "hedgehog_action_planning_steps: 0",
        "hedgehog_unbounded_authority_risk_units: 0",
        "hedgehog_blocked_authority_attempts: 18",
        "",
        "This is proof-level estimate only, not real billing, not real latency, and "
        "not a production cost claim.",
        "",
        "real_cost_savings_claimed: false",
        "real_latency_measured: false",
        "real_billing_measured: false",
        "",
        "7. ROOT FINAL",
        "",
        "Root Final: NOT_READY.",
        "Safe next step: NEEDS HUMAN REVIEW.",
        "No shipment approved.",
        "No payment triggered.",
        "No external action executed.",
        "No production claim created.",
        "",
        "root_final_status: not_ready",
        "safe_secondary_outcome: needs_human_review",
        f"production_claim_created: {_bool(root['production_claim_created'])}",
        "",
        "Conflict reasons:",
        "",
        "- stale_compliance_certificate",
        "- invoice_po_conflict",
        "- missing_payment_approval",
        "- real_action_not_authorized",
        "",
        "8. WHAT HUMAN SEES",
        "",
        "The human sees a system that can read a messy enterprise situation, "
        "understand why it is tempting to approve, explain why it must not approve, "
        "block authority escalation, and still reduce repeated reasoning.",
        "",
        "9. WHAT THIS PROVES",
        "",
        "- already proven layers can be assembled into one coherent enterprise demo",
        "- Root final boundary survives dirty enterprise inputs",
        "- connector observations are not truth",
        "- evidence candidates require acceptance gates",
        "- LLM drafts do not become final decisions",
        "- DRS reuse is context, not authority",
        "- Developer Facade remains candidate-only",
        "- Transition Matrix blocks invalid external action",
        "- Production Boundary blocks production overclaim",
        "- compute collapse can be shown as proof-level estimate",
        "",
        "10. WHAT THIS DOES NOT PROVE",
        "",
        "- production readiness",
        "- real API integration",
        "- real external action",
        "- real shipment release",
        "- real payment trigger",
        "- production persistence",
        "- real cost savings",
        "- real latency measurements",
        "- real billing measurements",
        "- installed capability",
        "- installed Needle",
        "- External/global DRS",
        "- Marennya / UP activation",
        "",
        "11. KILLER HUMAN MOMENT",
        "",
        "The system did not become an autonomous agent.",
        "It became a controlled semantic runtime.",
        "",
        "In plain English: it refused unsafe autonomy, preserved meaning, and left the final decision with Root.",
        "",
        "12. FINAL HUMAN SUMMARY",
        "",
        "Enterprise Killer Demo v0.1 proof is committed at 23a0cfe.",
        "It is an assembly of proven layers.",
        "ACT 1 shows dirty enterprise request.",
        "ACT 2 blocks 18 authority escalation attempts.",
        "ACT 3 shows proof-level compute collapse.",
        "Root Final is not_ready.",
        "Safe next step is needs_human_review.",
        "No real action is executed.",
        "No production claim is made.",
        "Human walkthrough is ready.",
        "Next lifecycle step after this walkthrough is audit log, then docs sync.",
        "",
        f"enterprise_killer_demo_v01_status: {summary['enterprise_killer_demo_v01_status']}",
        f"proof_type: {summary['proof_type']}",
        f"scenario_id: {summary['scenario_id']}",
        f"conflict_detected: {_bool(summary['conflict_detected'])}",
        f"act_count: {summary['act_count']}",
        f"human_walkthrough_ready: {_bool(summary['human_walkthrough_ready'])}",
        "no_network: true",
        "no_gemini: true",
        "no_real_api: true",
        "no_real_external_action: true",
        "no_production_persistence: true",
        "no_installed_capability: true",
        "no_installed_needle: true",
        "no_marennya: true",
        "no_up: true",
    ]

    return "\n".join(lines) + "\n"


def main() -> int:
    report = collect_enterprise_killer_demo_v01()
    print(render_human_enterprise_killer_demo_walkthrough_v01(report))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
