from __future__ import annotations

from typing import Any

from demo.run_bounded_llm_slm_actors_v01 import SCENARIOS, run_all_scenarios


TITLE = "HEDGEHOG OS — HUMAN BOUNDED LLM/SLM ACTORS WALKTHROUGH v0.1"

REQUIRED_COUNTERS = {
    "scenarios_total": 12,
    "scenarios_passed": 12,
    "final_output_created_count": 0,
    "action_permission_granted_count": 0,
    "actor_authority_claimed_count": 0,
    "llm_truth_claimed_count": 0,
    "slm_truth_claimed_count": 0,
    "model_confidence_authority_claimed_count": 0,
    "prompt_injection_escalation_count": 0,
    "actor_self_promotion_count": 0,
    "raw_advisory_command_accepted_count": 0,
    "raw_drs_memory_instruction_accepted_count": 0,
    "root_boundary_bypass_count": 0,
    "post_vv_bypass_count": 0,
    "gt_bypass_count": 0,
    "manifest_mutation_count": 0,
    "transition_matrix_mutation_count": 0,
    "network_used_count": 0,
    "gemini_used_count": 0,
    "connector_side_effect_count": 0,
    "root_final_authority_preserved_count": 12,
}

SECTION_HEADINGS = (
    "WHAT THIS WALKTHROUGH IS",
    "WHY THIS LAYER MATTERS",
    "CORE RULE",
    "ACT 1 — INTAKE MAY NORMALIZE, NOT DECIDE",
    "ACT 2 — ORCHESTRATOR CONSUMES SIGNALS, NOT COMMANDS",
    "ACT 3 — ARCHITECT RECEIVES ONLY ROOT-SHAPED TASKS",
    "ACT 4 — EXECUTOR RECEIVES ONLY BOUNDED PLANGRAPH",
    "ACT 5 — VERIFIER / POST V&V VALIDATES, NOT FINALIZES",
    "ACT 6 — PROMPT INJECTION CANNOT PROMOTE ACTOR TO ROOT",
    "ACT 7 — TARGET BOUNDARY FIX",
    "ACT 8 — CANONICAL CHAIN IS STILL ALLOWED",
    "ACT 9 — ROOT FINAL AUTHORITY PRESERVED",
    "COUNTERS",
    "VALIDATION SUMMARY",
    "LIMITATIONS",
    "FINAL HUMAN SUMMARY",
)

CANONICAL_CHAIN = (
    "intake -> Root/Orchestrator",
    "Root-shaped route -> Architect",
    "PlanGraph -> Executor",
    "ResultProposal -> Verifier/Post V&V",
    "VVReport -> GT boundary",
    "GTReport -> Root return",
    "Root return -> Root/Orchestrator",
)

DANGEROUS_TRANSITIONS = (
    "Architect PlanGraph -> final_output",
    "Architect PlanGraph -> root_return",
    "Executor ResultProposal -> final_output",
    "Executor ResultProposal -> root_return",
    "Verifier VVReport -> final_output",
    "Verifier VVReport -> root_return",
    "GTReport -> final_output",
    "GTReport -> Architect",
)


def _required_counters_match(result: dict[str, Any]) -> bool:
    observed = {
        "scenarios_total": result["scenarios_total"],
        "scenarios_passed": result["scenarios_passed"],
        **result["counters"],
    }
    return (
        result["final_status"] == "PASS"
        and all(observed.get(key) == expected for key, expected in REQUIRED_COUNTERS.items())
    )


def build_walkthrough() -> str:
    result = run_all_scenarios()
    counters = result["counters"]
    counters_match = _required_counters_match(result)

    lines = [
        TITLE,
        "",
        "WHAT THIS WALKTHROUGH IS",
        "This walkthrough explains the already audited Bounded LLM/SLM Actors v0.1 runtime.",
        "It creates no new runtime capability, no autonomous actor, no production LLM, no production SLM, no Gemini activation, no network, no FinalOutput, and no Root behavior modification.",
        "This layer does NOT create autonomous agents.",
        "This layer does NOT activate LLM/SLM/Gemini/network.",
        "",
        "WHY THIS LAYER MATTERS",
        "Previous runtime layers created:",
        "- Real Local DRS Resolver",
        "- CandidateVectorGenerator + AVF scoring",
        "- AVF Candidate Advisory Evaluator",
        "Those layers produce memory candidates, vectors, scores, and advisory route signals.",
        "Bounded LLM/SLM Actors v0.1 answers:",
        "- who may receive those signals",
        "- who may propose a route",
        "- who may call Architect",
        "- who may produce a PlanGraph",
        "- who may execute",
        "- who may verify",
        "- who must return to Root",
        "Fractal Cell Runtime integration depends on these bounded actor contracts.",
        "Actor roles covered: Intake Actor, Orchestrator Actor, Architect Actor, Executor Actor, Verifier/Post V&V, GT boundary, Root return.",
        "",
        "CORE RULE",
        "actor output is not truth",
        "actor output is not authority",
        "actor output is not action permission",
        "actor output is not FinalOutput",
        "LLM output is not truth",
        "SLM output is not truth",
        "model confidence is not authority",
        "tool capability is not permission",
        "route proposal is not Root decision",
        "PlanGraph proposal is not execution authority",
        "ResultProposal is not FinalOutput",
        "advisory report is not command",
        "Root remains final authority",
        "",
        "ACT 1 — INTAKE MAY NORMALIZE, NOT DECIDE",
        "intake_actor_normalizes_intent_without_authority",
        "Intake can normalize intent and context, but cannot decide, execute, write final output, or grant permission.",
        "",
        "ACT 2 — ORCHESTRATOR CONSUMES SIGNALS, NOT COMMANDS",
        "orchestrator_actor_consumes_advisory_report_as_signal_only",
        "orchestrator_route_proposal_requires_root_boundary",
        "Orchestrator can consume DRS/AVF/advisory reports as signals and propose Root-shaped routes.",
        "A route proposal is not Root decision.",
        "",
        "ACT 3 — ARCHITECT RECEIVES ONLY ROOT-SHAPED TASKS",
        "architect_actor_accepts_only_root_shaped_task",
        "architect_actor_outputs_plangraph_proposal_only",
        "Architect cannot be commanded by raw user text, AVF/advisory signals, or DRS memory.",
        "Architect receives only Root-shaped tasks/routes.",
        "Architect outputs PlanGraph proposal only.",
        "",
        "ACT 4 — EXECUTOR RECEIVES ONLY BOUNDED PLANGRAPH",
        "executor_actor_accepts_only_bounded_plangraph",
        "executor_actor_outputs_resultproposal_only",
        "Executor cannot create FinalOutput.",
        "Executor consumes bounded PlanGraph only and returns ResultProposal-like bounded output.",
        "",
        "ACT 5 — VERIFIER / POST V&V VALIDATES, NOT FINALIZES",
        "verifier_actor_validates_without_finaloutput",
        "Verifier/Post V&V validates ResultProposal-like output.",
        "It cannot create Root Final or grant action permission.",
        "",
        "ACT 6 — PROMPT INJECTION CANNOT PROMOTE ACTOR TO ROOT",
        "prompt_injection_cannot_promote_actor_to_root",
        "actor_role_confusion_is_blocked",
        "model_confidence_does_not_create_authority",
        "Prompt injection cannot change actor role.",
        "An actor cannot self-promote to Root.",
        "Model confidence is advisory metadata, not authority.",
        "",
        "ACT 7 — TARGET BOUNDARY FIX",
        "Target Boundary Fix",
        "The audit found and recorded the most important boundary: it is not enough to check what an actor outputs; the system must check where the output is being sent.",
        "Blocked dangerous transitions:",
        *DANGEROUS_TRANSITIONS,
        "Reason code: final_output_target_boundary_blocked",
        "",
        "ACT 8 — CANONICAL CHAIN IS STILL ALLOWED",
        *CANONICAL_CHAIN,
        "This is the safe skeleton future Fractal Cell Runtime will depend on.",
        "",
        "ACT 9 — ROOT FINAL AUTHORITY PRESERVED",
        "root_final_authority_preserved_across_actor_chain",
        "All actors return bounded artifacts or reports.",
        "Root remains final authority.",
        "",
        "COUNTERS",
        f"underlying_runtime_status: {result['final_status']}",
        f"scenarios_total: {result['scenarios_total']}",
        f"scenarios_passed: {result['scenarios_passed']}",
        f"actor_inputs_seen_count: {counters['actor_inputs_seen_count']}",
        f"actor_outputs_emitted_count: {counters['actor_outputs_emitted_count']}",
        f"intake_outputs_count: {counters['intake_outputs_count']}",
        f"route_proposals_count: {counters['route_proposals_count']}",
        f"plangraph_proposals_count: {counters['plangraph_proposals_count']}",
        f"result_proposals_count: {counters['result_proposals_count']}",
        f"validation_reports_count: {counters['validation_reports_count']}",
        f"root_review_required_count: {counters['root_review_required_count']}",
        f"final_output_created_count: {counters['final_output_created_count']}",
        f"action_permission_granted_count: {counters['action_permission_granted_count']}",
        f"actor_authority_claimed_count: {counters['actor_authority_claimed_count']}",
        f"llm_truth_claimed_count: {counters['llm_truth_claimed_count']}",
        f"slm_truth_claimed_count: {counters['slm_truth_claimed_count']}",
        f"model_confidence_authority_claimed_count: {counters['model_confidence_authority_claimed_count']}",
        f"prompt_injection_escalation_count: {counters['prompt_injection_escalation_count']}",
        f"actor_self_promotion_count: {counters['actor_self_promotion_count']}",
        f"raw_advisory_command_accepted_count: {counters['raw_advisory_command_accepted_count']}",
        f"raw_drs_memory_instruction_accepted_count: {counters['raw_drs_memory_instruction_accepted_count']}",
        f"root_boundary_bypass_count: {counters['root_boundary_bypass_count']}",
        f"post_vv_bypass_count: {counters['post_vv_bypass_count']}",
        f"gt_bypass_count: {counters['gt_bypass_count']}",
        f"manifest_mutation_count: {counters['manifest_mutation_count']}",
        f"transition_matrix_mutation_count: {counters['transition_matrix_mutation_count']}",
        f"network_used_count: {counters['network_used_count']}",
        f"gemini_used_count: {counters['gemini_used_count']}",
        f"connector_side_effect_count: {counters['connector_side_effect_count']}",
        f"root_final_authority_preserved_count: {counters['root_final_authority_preserved_count']}",
        f"walkthrough_required_counters_match: {counters_match}",
        "",
        "VALIDATION SUMMARY",
        "- runtime commit: 6802d14",
        "- technical audit: dfd43b9",
        "- targeted tests: 92 passed, 50 warnings",
        "- full pytest: 1819 passed, 60 warnings",
        "- runner: FINAL STATUS: PASS",
        "",
        "LIMITATIONS",
        "No production LLM autonomy.",
        "No production SLM autonomy.",
        "No real model calls.",
        "No Gemini activation.",
        "No network.",
        "No embeddings.",
        "No external tool calls.",
        "No connector side effects.",
        "No autonomous action.",
        "No Fractal Cell Runtime integration in this layer.",
        "No Root behavior modification.",
        "No Architect command from AVF/advisory evaluator.",
        "No Executor command from LLM actor without Root-shaped route.",
        "No FinalOutput creation.",
        "No action permission.",
        "No direct reuse permission.",
        "No manifest mutation.",
        "No transition matrix mutation.",
        "No Marennya/UP.",
        "No public WOW.",
        "No whitepaper/public auditor packet.",
        "Real Semantic Runtime MVP is not complete.",
        "",
        "FINAL HUMAN SUMMARY",
        "Hedgehog OS now has a role-boundary skeleton for bounded actors.",
        "Intake, Orchestrator, Architect, Executor, Verifier/Post V&V, GT boundary, and Root return each have allowed inputs, allowed outputs, and forbidden transitions.",
        "This does not make autonomous agents.",
        "It prevents role confusion before Fractal Cell Runtime integration.",
        "Actors cannot self-promote, cannot command sideways, cannot create FinalOutput, and cannot bypass Root.",
        "Root remains final authority.",
        "",
        "scenario coverage:",
        *SCENARIOS,
    ]
    return "\n".join(lines)


def main() -> int:
    output = build_walkthrough()
    print(output)
    return 0 if "walkthrough_required_counters_match: True" in output else 1


if __name__ == "__main__":
    raise SystemExit(main())
